app:
  hosts:
    appserver:
      ansible_host: 10.132.15.210
db:
  hosts:
    dbserver:
      ansible_host: 10.132.15.209

ansible:
  hosts:
    workstation:
      ansible_host: 10.132.0.59

      
